# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: JS and C++ Formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  js-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'

      - run: yarn install
      - run: yarn format:check

  cpp-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check C++ formatting with clang-format
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: './src'
          exclude: './src/mio ./src/xxhash ./src/zstr'
          extensions: 'h,c,cpp,hpp'
          clangFormatVersion: 12
